Add NatSpec to WETH10.sol
wETH-v2/wETH-v2 pull request #29
Opened 2020-10-14 23:53 UTC by Ro5s

add NatSpec per https://github.com/wETH-v2/wETH-v2/issues/26

2020-10-15 08:06 UTC, albertocuestacanada requested changes
Some code was accidentally reverted, please fix.
Other than that, very minor requests, thanks for doing this!

2020-10-15 08:06 UTC, albertocuestacanada commented on contracts/WETH10.sol
> +     * @dev Returns the amount of WETH10 token owned by an account.
I would say "Records" instead of "Returns", same for all other state variables (nonces, allowance)

2020-10-15 08:06 UTC, albertocuestacanada commented on contracts/WETH10.sol
> +    uint256 private unlocked = 1;
Trailing whitespace. Please run `yarn lint:sol` to find linting errors before pushing.

2020-10-15 08:06 UTC, albertocuestacanada commented on contracts/WETH10.sol
> -
I'm not sure if you branched before pulling, but here you are undoing one of the recent PRs. The code in red is the right version.

2020-10-15 08:06 UTC, albertocuestacanada commented on contracts/WETH10.sol
> -    // Adapted from https://github.com/albertocuestacanada/ERC20Permit/blob/master/contracts/ERC20Permit.sol
:+1:

2020-10-15 08:06 UTC, albertocuestacanada commented on contracts/WETH10.sol
Same as before, code in red is the right version.

2020-10-16 20:49 UTC, Ro5s commented
thanks for the great comments here @albertocuestacanada // I am deprecating this PR in favor of another, which has an updated base for WETH.sol and includes some additional `internal` functions, syntax tweaks: https://github.com/wETH-v2/wETH-v2/pull/32

2020-10-16 20:49 UTC, closed without merging